Repository DaPulse/strong-params, pull requests merged in 2022-03, with the labels that each got.

#3 fixed failure when params have an object with key = toString
  lib/parameters.js
  package-lock.json
  package.json
Labels: PR: partially-approved

#6 feat: upgrade lodash to 4.17.21
  package-lock.json
  package.json
Labels: PR: unreviewed

#7 bump patch version (lodash version was upgraded)
  package-lock.json
  package.json
Labels: PR: reviewed-approved
